### ISSUE TITLE
Tukey full on NaN

### ISSUE THREAD

**Issue by jjb-hub** [jjb-hub/phd#23]
5HIAA/5HT in SC histogram for dose_response the data is not being put through to the stats correctly as it is full of NaN
![Screen Shot 2023-09-28 at 15 23 02](https://github.com/jjb-hub/phd/assets/120100465/e2a5f385-df7d-4c84-8bcb-6dda80a23a64)

_Originally posted by @jjb-hub in https://github.com/jjb-hub/phd/issues/14#issuecomment-1739161523_

**Comment by remicorne** [comment]
@jjb-hub Please give as much information as you can, you didnt specify the experiment.  Ofc I can deduce it from the groups but it won't always be like that. Also I don't for the life of me understand why you cut your screenshots. You don't pay per pixel, just capture the whole freaking screen!! You never know what i might need and in this case having the figure to compare would be nice because things are working fine for me
![image](https://github.com/jjb-hub/phd/assets/59827951/13da1f74-78d0-4452-aba5-e9ddeca196da)

**Comment by jjb-hub** [comment]
occured to NaN not being removed before being fed to one way anova so returned NaN FIXED
